### ISSUE TITLE
Not really an issue but ..

### ISSUE THREAD

**Issue by CredenceHamby** [Jericho1060/du-storage-monitoring#4]
i couldnt find another way to get ahold of you. Anyway we can get a version of this that will just pick up a container thats holding multiple ores and show the levels? Like we would name the container with only (s1) or (s2) and would show the resources inside? Would be willing to pay for it. i know others have this function but yours is the best looking and easiest to work with. 

Or would be better actually if on your mining units monitor we could choose a second screen to output the container contents that the units get dumped into.

**Comment by thoda-dev** [comment]
Sorry for late answer.

There is currently two questions here :
- monitoring the mining unit container output : this is not the goal of that project, it's currently something i'm thinking about to add on my mining unit script, ons one side it's easy to do, on a second side, there some limitation: it's adding the need of two more slots on the script so potentially taking too much slots for mining units. (2 screens + 1 container + x mining units) i own several tiles where i would then need two board to monitor my mining units because of slots. Several bad point: there is a query limit on the container API that can easilly lock you and make the script bug as we have no way to see if the player can or not still query the api.
- about another script that is specialized in seeing the content of one single container doesn't matter how many items it contains : it's not the goal of that storage script that is optimized to monitor really large storage areas (more an industry usage). About another script to do it: i have made one but i'm currently not distributing it as like explained before, there can be problems with the query limit.

On a more general goal, i'm mainly waiting for a decision about the wipe. Currently, I'm giving several scripts for free because i d'ont need any money in the game. As scripting is currently my main gameplay, if a wipe is done, i'll need to make some cash again and then, will probably sell some scripts that's why some scripts i made and for some announced, are not released to public yet. Waiting for the decision from NQ.
